name: CI
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    if: ${{ !contains(github.event.head_commit.message, 'docker image') }}
    name: "Build and Push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generete SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      - name: Login into the container reggistry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nlwjorney:${{ steps.generate_sha.outputs.sha }} .
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nlwjorney:${{ steps.generate_sha.outputs.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nlwjorney:${{ steps.generate_sha.outputs.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/nlwjorney:lastest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nlwjorney:lastest
